### ISSUE TITLE
Controlar intersecciones

### ISSUE THREAD

**Issue by acontursi** [acontursi/DPV-SIGIV#1]
Revisar las intersecciones entre las Rutas Nacionales y Provinciales.
Identificar tipos de intersecciones y si existen nuevos diseños geométricos que agregar a las capas.
Determinar jurisdicción del acceso.

**Comment by ANDYAGUIRRE10** [comment]
**Rutas provinciales**. 
Se crea un campo "Enlaces". 'si': controlado
